# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.1'

services:
  ca0:
    hostname: ca0
    network_mode: "host"
    image: hyperledger/fabric-ca:1.4.1
    environment:
      - GODEBUG=netdns=go
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3e96dde14b6926dfe6fffcd23b2425d1aa84628d671e9a5ac1b17ada7abeada8_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/3e96dde14b6926dfe6fffcd23b2425d1aa84628d671e9a5ac1b17ada7abeada8_sk -b admin:adminpw -d'
    volumes:
      - ../../config/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ${MOUNT_PATH}/ca0/fabric-ca-server:/etc/hyperledger/fabric-ca-server
    container_name: ca_peerOrg1
