# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file: ../../base/docker-compose-base.yaml
      service: peer0.org2.example.com
    networks:
      - byfn

  orderer4.example.com:
    extends:
      file: ../../base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.example.com
    networks:
      - byfn
    volumes:
      - /etc/hosts:/etc/hosts
      - ../../config/channel-artifacts/${GENESIS_BLOCK}:/var/hyperledger/orderer/orderer.genesis.block
      - ../../config/crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/msp:/var/hyperledger/orderer/msp
      - ../../config/crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/:/var/hyperledger/orderer/tls
      - /tmp/orderer4.example.com:/var/hyperledger/production
    ports:
#      - 6060:6060
      - 6101:6101
      - 7050:7050
