version: '2'

services:
  zoo3:
    image: zookeeper:3.4.14
    restart: always
    network_mode: "host"
    hostname: 'zoo3'
    container_name: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
