# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
    byfn:
services:
    ca0:
        image: hyperledger/fabric-ca:1.4.1
        environment:
            - GODEBUG=netdns=go
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-org1
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3e96dde14b6926dfe6fffcd23b2425d1aa84628d671e9a5ac1b17ada7abeada8_sk
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/3e96dde14b6926dfe6fffcd23b2425d1aa84628d671e9a5ac1b17ada7abeada8_sk -b admin:adminpw -d'
        volumes:
            - /etc/hosts:/etc/hosts
            - ../../config/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
        container_name: ca_peerOrg1
        networks:
            - byfn

    orderer.example.com:
        extends:
            file: ../../base/peer-base.yaml
            service: orderer-base
        container_name: orderer.example.com
        networks:
            - byfn
        volumes:
            - /etc/hosts:/etc/hosts
            - ../../config/channel-artifacts/${GENESIS_BLOCK}:/var/hyperledger/orderer/orderer.genesis.block
            - ../../config/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
            - ../../config/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        ports:
            - 6060:6060
            - 6101:6101
            - 7050:7050

    zookeeper0:
        container_name: zookeeper0
        image: hyperledger/fabric-zookeeper:latest
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_TICK_TIME=2000
            - ZOO_MY_ID=1
            - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
        ports:
            - 2181:2181
        networks:
            - byfn

    kafka0:
        container_name: kafka0
        image: hyperledger/fabric-kafka:latest
        depends_on:
            - zookeeper0
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka0:9092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_MESSAGE_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
            - KAFKA_REPLICA_FETCH_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MIN_INSYNC_REPLICAS=1
            - KAFKA_DEFAULT_REPLICATION_FACTOR=1
        networks:
            - byfn

