# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
    byfn:
services:
    peer0.org1.example.com:
        container_name: peer0.org1.example.com
        extends:
            file: ../../base/docker-compose-base.yaml
            service: peer0.org1.example.com
        networks:
            - byfn

    orderer3.example.com:
        extends:
            file: ../../base/peer-base.yaml
            service: orderer-base
        container_name: orderer3.example.com
        networks:
            - byfn
        volumes:
            - /etc/hosts:/etc/hosts
            - ../../config/channel-artifacts/${GENESIS_BLOCK}:/var/hyperledger/orderer/orderer.genesis.block
            - ../../config/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/orderer/msp
            - ../../config/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/:/var/hyperledger/orderer/tls
        ports:
            - 6060:6060
            - 6101:6101
            - 7050:7050

    kafka2:
        container_name: kafka2
        image: hyperledger/fabric-kafka:latest
        depends_on:
            - zookeeper2
        environment:
            - KAFKA_BROKER_ID=3
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_MESSAGE_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
            - KAFKA_REPLICA_FETCH_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MIN_INSYNC_REPLICAS=1
            - KAFKA_DEFAULT_REPLICATION_FACTOR=1
        volumes:
            - /etc/hosts:/etc/hosts
        networks:
            - byfn
