---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 1
  rounds:
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 50
    arguments:
      money: 10000
    callback: benchmark/simple/open.js
  - label: query
    description: Test description for the query performance of the deployed chaincode
    txNumber:
    - 100
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    callback: benchmark/simple/query.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
#    - http://192.168.0.84:2375/ca_peerOrg1
#    - http://192.168.0.92:2375/ca_peerOrg2
#    - http://192.168.0.91:2375/peer0.org1.example.com
#    - http://192.168.0.93:2375/peer0.org2.example.com
#    - http://192.168.0.84:2375/orderer.example.com
#    - http://192.168.0.92:2375/orderer2.example.com
#    - http://192.168.0.91:2375/orderer3.example.com
#    - http://192.168.0.93:2375/orderer4.example.com
#    - http://192.168.0.93:2375/orderer5.example.com
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
